### ISSUE TITLE
未知类型的消息引发空指针错误

### ISSUE THREAD

**Issue by HollisMeynell** [MisakaTAT/Shiro#186]
**当前结果**
发送qq内置的表情包时, 使用shamrock框架链接百分百出错

临时解决方案: 修改 [此处](https://github.com/MisakaTAT/Shiro/blob/be55c03574d7d293ad852cc38b165bc2c34bc7e9/src/main/java/com/mikuac/shiro/common/utils/ShiroUtils.java#L249)
为` if (!MsgTypeEnum.text.equals(item.getType()))`

下面是错误信息:
Message event process exception: Cannot invoke "com.mikuac.shiro.enums.MsgTypeEnum.equals(Object)" because the return value of "com.mikuac.shiro.model.ArrayMsg.getType()" is null

java.lang.NullPointerException: Cannot invoke "com.mikuac.shiro.enums.MsgTypeEnum.equals(Object)" because the return value of "com.mikuac.shiro.model.ArrayMsg.getType()" is null
	at com.mikuac.shiro.common.utils.ShiroUtils.arrayMsgToCode(ShiroUtils.java:249) ~[shiro-2.1.3.jar:na]
	at com.mikuac.shiro.common.utils.ShiroUtils.rawConvert(ShiroUtils.java:218) ~[shiro-2.1.3.jar:na]
	at com.mikuac.shiro.handler.event.MessageEvent.process(MessageEvent.java:104) ~[shiro-2.1.3.jar:na]
	at com.mikuac.shiro.handler.event.MessageEvent.group(MessageEvent.java:144) ~[shiro-2.1.3.jar:na]
	at com.mikuac.shiro.handler.event.MessageEvent.handler(MessageEvent.java:63) ~[shiro-2.1.3.jar:na]
	at com.mikuac.shiro.handler.EventHandler.handler(EventHandler.java:121) ~[shiro-2.1.3.jar:na]
	at com.mikuac.shiro.task.ShiroAsyncTask.execHandlerMsg(ShiroAsyncTask.java:38) ~[shiro-2.1.3.jar:na]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[na:na]
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343) ~[spring-aop-6.0.12.jar:6.0.12]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196) ~[spring-aop-6.0.12.jar:6.0.12]

**Comment by MisakaTAT** [comment]
Fixed
