### ISSUE TITLE
2.1.9版本正向ws发送消息出错

### ISSUE THREAD

**Issue by Origin1699** [MisakaTAT/Shiro#204]
**详细描述**
2.1.9版本使用正向ws连接onebot服务器, 发送消息出错

**屏幕截图或者日志**
报错日志:
```
2024-03-25 15:08:38.801 ERROR 26368 --- [ShiroTaskPool-5] c.m.s.h.injection.InjectionHandler       : Invoke method exception: null
java.lang.reflect.InvocationTargetException: null
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
	at com.mikuac.shiro.handler.injection.InjectionHandler.invokeMethod(InjectionHandler.java:47) ~[shiro-2.1.9.jar:na]
	at com.mikuac.shiro.handler.injection.InjectionHandler.invoke(InjectionHandler.java:72) ~[shiro-2.1.9.jar:na]
	at com.mikuac.shiro.handler.injection.InjectionHandler.lambda$invokeMessage$2(InjectionHandler.java:257) ~[shiro-2.1.9.jar:na]
	at java.base/java.lang.Iterable.forEach(Iterable.java:75) ~[na:na]
	at com.mikuac.shiro.handler.injection.InjectionHandler.invokeMessage(InjectionHandler.java:251) ~[shiro-2.1.9.jar:na]
	at com.mikuac.shiro.handler.injection.InjectionHandler.invokeGroupMessage(InjectionHandler.java:225) ~[shiro-2.1.9.jar:na]
	at com.mikuac.shiro.handler.event.MessageEvent.process(MessageEvent.java:107) ~[shiro-2.1.9.jar:na]
	at com.mikuac.shiro.handler.event.MessageEvent.group(MessageEvent.java:144) ~[shiro-2.1.9.jar:na]
	at com.mikuac.shiro.handler.event.MessageEvent.handler(MessageEvent.java:63) ~[shiro-2.1.9.jar:na]
	at com.mikuac.shiro.handler.EventHandler.handler(EventHandler.java:121) ~[shiro-2.1.9.jar:na]
	at com.mikuac.shiro.task.ShiroAsyncTask.execHandlerMsg(ShiroAsyncTask.java:38) ~[shiro-2.1.9.jar:na]
	at com.mikuac.shiro.task.ShiroAsyncTask$$FastClassBySpringCGLIB$$bf2eb263.invoke(<generated>) ~[shiro-2.1.9.jar:na]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.23.jar:5.3.23]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793) ~[spring-aop-5.3.23.jar:5.3.23]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.3.23.jar:5.3.23]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) ~[spring-aop-5.3.23.jar:5.3.23]
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115) ~[spring-aop-5.3.23.jar:5.3.23]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
Caused by: com.mikuac.shiro.exception.ShiroException$SessionCloseException: session been closed.
	at com.mikuac.shiro.handler.ActionHandler.action(ActionHandler.java:108) ~[shiro-2.1.9.jar:na]
	at com.mikuac.shiro.core.Bot.sendGroupMsg(Bot.java:163) ~[shiro-2.1.9.jar:na]
	at top.ikaori.bot.common.util.MessageUtil.sendGroupMsg(MessageUtil.java:41) ~[classes/:na]
	at top.ikaori.bot.common.util.MessageUtil.sendMsg(MessageUtil.java:72) ~[classes/:na]
	at top.ikaori.bot.core.aop.CommandAspect.groupPrefixCheck(CommandAspect.java:77) ~[classes/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:634) ~[spring-aop-5.3.23.jar:5.3.23]
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:624) ~[spring-aop-5.3.23.jar:5.3.23]
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:72) ~[spring-aop-5.3.23.jar:5.3.23]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175) ~[spring-aop-5.3.23.jar:5.3.23]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) ~[spring-aop-5.3.23.jar:5.3.23]
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97) ~[spring-aop-5.3.23.jar:5.3.23]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.23.jar:5.3.23]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) ~[spring-aop-5.3.23.jar:5.3.23]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708) ~[spring-aop-5.3.23.jar:5.3.23]
	at top.ikaori.bot.plugins.Dao$$EnhancerBySpringCGLIB$$c6dfc5ea.dao(<generated>) ~[classes/:na]
	... 25 common frames omitted
```
启动日志, 中ws连接是正常的:
```
2024-03-25 15:11:03.371  INFO 10064 --- [           main] o.s.w.s.c.WebSocketConnectionManager     : Connecting to WebSocket at ws://********:3001
2024-03-25 15:11:03.540  INFO 10064 --- [cTaskExecutor-1] c.mikuac.shiro.adapter.WebSocketClient   : Account 379201421 connected
2024-03-25 15:11:03.547  INFO 10064 --- [cTaskExecutor-1] o.s.w.s.c.WebSocketConnectionManager     : Successfully connected
```

**运行或开发环境**

- 系统版本：win10
- Shiro版本：2.1.9
- 客户端版本：llonebot
- JDK版本：jdk17
- SpringBoot版本：2.7.5

**Comment by MisakaTAT** [comment]
Fixed in 4131ba949673b0a280ce774f6d7a3ae5159bf349
